version: 2.1
workflows:
  testing:
    jobs:
      - test
      - build-ipa:
          requires:
                - test

      
jobs:
  test:
    machine: true
    resource_class: nathansepul/class_appollo
    steps:
      - checkout
      - run: echo 'test'
      # - run: flutter test

  build-ipa:
    machine: true
    resource_class: nathansepul/class_appollo
    steps:
      - checkout
      - run: echo 'build ipa'
      # - run: appollo signin --email <email> --password <password>
      # - run: appollo build start --build-type=ad-hoc <application_key>
      # - run: appollo signout
