version: 2.1
workflows:
  testing:
    jobs:
      - test
      - build-ipa:
          requires:
            - test
          filters:
            branches:
              ignore: 
                - production

      - deploy:
          requires:
            - test
          filters:
            branches:
              only: production

      
jobs:
  test:
    machine: true
    resource_class: nathansepul/class_appollo
    steps:
      - checkout
      - run: echo 'test'
      # - run: flutter test

  build-ipa:
    machine: true
    resource_class: nathansepul/class_appollo
    steps:
      - run: echo 'build ipa'
      - checkout
      # - run: appollo signin --email <email> --password <password>
      - run: appollo build start --build-type=ad-hoc 882
      # - run: appollo signout

  deploy:
    machine: true
    resource_class: nathansepul/class_appollo
    steps:
      - checkout
      - run: echo 'Publication app'
      # - run: appollo signin --email <email> --password <password>
      # - run: appollo build start --build-type=publication <application_key>
      # - run: appollo signout
